/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module laneconvert_9 (
    input [15:0] lanein,
    output reg [23:0] laneout
  );
  
  
  
  wire [3-1:0] M_c1_out;
  reg [2-1:0] M_c1_in;
  convertsingleled_26 c1 (
    .in(M_c1_in),
    .out(M_c1_out)
  );
  
  wire [3-1:0] M_c2_out;
  reg [2-1:0] M_c2_in;
  convertsingleled_26 c2 (
    .in(M_c2_in),
    .out(M_c2_out)
  );
  
  wire [3-1:0] M_c3_out;
  reg [2-1:0] M_c3_in;
  convertsingleled_26 c3 (
    .in(M_c3_in),
    .out(M_c3_out)
  );
  
  wire [3-1:0] M_c4_out;
  reg [2-1:0] M_c4_in;
  convertsingleled_26 c4 (
    .in(M_c4_in),
    .out(M_c4_out)
  );
  
  wire [3-1:0] M_c5_out;
  reg [2-1:0] M_c5_in;
  convertsingleled_26 c5 (
    .in(M_c5_in),
    .out(M_c5_out)
  );
  
  wire [3-1:0] M_c6_out;
  reg [2-1:0] M_c6_in;
  convertsingleled_26 c6 (
    .in(M_c6_in),
    .out(M_c6_out)
  );
  
  wire [3-1:0] M_c7_out;
  reg [2-1:0] M_c7_in;
  convertsingleled_26 c7 (
    .in(M_c7_in),
    .out(M_c7_out)
  );
  
  wire [3-1:0] M_c8_out;
  reg [2-1:0] M_c8_in;
  convertsingleled_26 c8 (
    .in(M_c8_in),
    .out(M_c8_out)
  );
  
  always @* begin
    M_c1_in = lanein[0+1-:2];
    M_c2_in = lanein[2+1-:2];
    M_c3_in = lanein[4+1-:2];
    M_c4_in = lanein[6+1-:2];
    M_c5_in = lanein[8+1-:2];
    M_c6_in = lanein[10+1-:2];
    M_c7_in = lanein[12+1-:2];
    M_c8_in = lanein[14+1-:2];
    laneout = ~({M_c8_out, M_c7_out, M_c6_out, M_c5_out, M_c4_out, M_c3_out, M_c2_out, M_c1_out});
  end
endmodule
